name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add ssh key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 176.124.219.190 >> ~/.ssh/known_hosts
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Chechout
        uses: actions/checkout@v6
      - name: deploy
        run: rsync index.html root@176.124.219.190:/var/www/html/
